lang: en_US
title: Strixx
author: Maximous Black
tagline: Open Directory Search Tool
description: Open Directory Search Tool

url: "https://maximousblk.github.io"
baseurl: "/strixx"

google_site_verification: 5jYtdwLS7gzPX2uag2JzUft_UtX5n54z-egEeUkftdg
google_analytics: UA-131672698-4

footer_url: "https://github.com/maximousblk/strixx/"
footer_text: "Star on GitHub"

logo: logo.svg
favicon: favicon.ico

sass:
    style: compressed
    sass_dir: css

plugins:
 - jekyll-seo-tag
